---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Splinets

<!-- badges: start -->
<!-- badges: end -->

# Overview

Splines are efficiently represented through their Taylor expansion at the knots. The representation accounts for the support sets and is thus suitable for sparse functional data. Two cases of boundary conditions are considered: zero-boundary or periodic-boundary for all derivatives except the last. The periodical splines are represented graphically using polar coordinates. The B-splines and orthogonal bases of splines that reside on small total support are implemented. The orthogonal bases are referred to as 'splinets' and are utilized for functional data analysis. Random spline generator is implemented as well as all fundamental algebraic and calculus operations on splines. The optimal, in the least square sense, functional fit by 'splinets' to data consisting of sampled values of functions as well as splines build over another set of knots is obtained and used for functional data analysis. <doi:10.48550/arXiv.2102.00733>, <doi:10.1016/j.cam.2022.114444>, <doi:10.48550/arXiv.2302.07552>.

## Installation

You can install Splinets package with the following code. 

``` r
install.packages("Splinets")
```

You can install the development version of Splinets from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("ranibasna/R-Splinets")
```



# Reproducing Papers results

For reproducing the results presented in the paper for the Image classification example, see [this link](https://ranibasna.github.io/R-Splinets/articles/ImageClassification.html)



